// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package wordservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WordServiceClient is the client API for WordService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WordServiceClient interface {
	AddWords(ctx context.Context, in *AddWordsRequest, opts ...grpc.CallOption) (*WordsResponse, error)
	UpdateWord(ctx context.Context, in *UpdateWordRequest, opts ...grpc.CallOption) (*WordsResponse, error)
	SearchWord(ctx context.Context, in *SearchWordRequest, opts ...grpc.CallOption) (*WordsResponse, error)
	TopSearches(ctx context.Context, in *TopSearchesRequest, opts ...grpc.CallOption) (*WordsResponse, error)
}

type wordServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWordServiceClient(cc grpc.ClientConnInterface) WordServiceClient {
	return &wordServiceClient{cc}
}

func (c *wordServiceClient) AddWords(ctx context.Context, in *AddWordsRequest, opts ...grpc.CallOption) (*WordsResponse, error) {
	out := new(WordsResponse)
	err := c.cc.Invoke(ctx, "/wordservice.WordService/AddWords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wordServiceClient) UpdateWord(ctx context.Context, in *UpdateWordRequest, opts ...grpc.CallOption) (*WordsResponse, error) {
	out := new(WordsResponse)
	err := c.cc.Invoke(ctx, "/wordservice.WordService/UpdateWord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wordServiceClient) SearchWord(ctx context.Context, in *SearchWordRequest, opts ...grpc.CallOption) (*WordsResponse, error) {
	out := new(WordsResponse)
	err := c.cc.Invoke(ctx, "/wordservice.WordService/SearchWord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wordServiceClient) TopSearches(ctx context.Context, in *TopSearchesRequest, opts ...grpc.CallOption) (*WordsResponse, error) {
	out := new(WordsResponse)
	err := c.cc.Invoke(ctx, "/wordservice.WordService/TopSearches", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WordServiceServer is the server API for WordService service.
// All implementations must embed UnimplementedWordServiceServer
// for forward compatibility
type WordServiceServer interface {
	AddWords(context.Context, *AddWordsRequest) (*WordsResponse, error)
	UpdateWord(context.Context, *UpdateWordRequest) (*WordsResponse, error)
	SearchWord(context.Context, *SearchWordRequest) (*WordsResponse, error)
	TopSearches(context.Context, *TopSearchesRequest) (*WordsResponse, error)
	mustEmbedUnimplementedWordServiceServer()
}

// UnimplementedWordServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWordServiceServer struct {
}

func (UnimplementedWordServiceServer) AddWords(context.Context, *AddWordsRequest) (*WordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddWords not implemented")
}
func (UnimplementedWordServiceServer) UpdateWord(context.Context, *UpdateWordRequest) (*WordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWord not implemented")
}
func (UnimplementedWordServiceServer) SearchWord(context.Context, *SearchWordRequest) (*WordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchWord not implemented")
}
func (UnimplementedWordServiceServer) TopSearches(context.Context, *TopSearchesRequest) (*WordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TopSearches not implemented")
}
func (UnimplementedWordServiceServer) mustEmbedUnimplementedWordServiceServer() {}

// UnsafeWordServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WordServiceServer will
// result in compilation errors.
type UnsafeWordServiceServer interface {
	mustEmbedUnimplementedWordServiceServer()
}

func RegisterWordServiceServer(s grpc.ServiceRegistrar, srv WordServiceServer) {
	s.RegisterService(&WordService_ServiceDesc, srv)
}

func _WordService_AddWords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordServiceServer).AddWords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wordservice.WordService/AddWords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordServiceServer).AddWords(ctx, req.(*AddWordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WordService_UpdateWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordServiceServer).UpdateWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wordservice.WordService/UpdateWord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordServiceServer).UpdateWord(ctx, req.(*UpdateWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WordService_SearchWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordServiceServer).SearchWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wordservice.WordService/SearchWord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordServiceServer).SearchWord(ctx, req.(*SearchWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WordService_TopSearches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopSearchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordServiceServer).TopSearches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wordservice.WordService/TopSearches",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordServiceServer).TopSearches(ctx, req.(*TopSearchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WordService_ServiceDesc is the grpc.ServiceDesc for WordService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WordService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wordservice.WordService",
	HandlerType: (*WordServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddWords",
			Handler:    _WordService_AddWords_Handler,
		},
		{
			MethodName: "UpdateWord",
			Handler:    _WordService_UpdateWord_Handler,
		},
		{
			MethodName: "SearchWord",
			Handler:    _WordService_SearchWord_Handler,
		},
		{
			MethodName: "TopSearches",
			Handler:    _WordService_TopSearches_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wordservice/wordservice.proto",
}
