// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.2
// source: wordservice/wordservice.proto

package wordservice

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchWordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SearchWordRequest) Reset() {
	*x = SearchWordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wordservice_wordservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchWordRequest) ProtoMessage() {}

func (x *SearchWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wordservice_wordservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchWordRequest.ProtoReflect.Descriptor instead.
func (*SearchWordRequest) Descriptor() ([]byte, []int) {
	return file_wordservice_wordservice_proto_rawDescGZIP(), []int{0}
}

func (x *SearchWordRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UpdateWordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrigValue string `protobuf:"bytes,1,opt,name=orig_value,json=origValue,proto3" json:"orig_value,omitempty"`
	NewValue  string `protobuf:"bytes,2,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
}

func (x *UpdateWordRequest) Reset() {
	*x = UpdateWordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wordservice_wordservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWordRequest) ProtoMessage() {}

func (x *UpdateWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wordservice_wordservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWordRequest.ProtoReflect.Descriptor instead.
func (*UpdateWordRequest) Descriptor() ([]byte, []int) {
	return file_wordservice_wordservice_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateWordRequest) GetOrigValue() string {
	if x != nil {
		return x.OrigValue
	}
	return ""
}

func (x *UpdateWordRequest) GetNewValue() string {
	if x != nil {
		return x.NewValue
	}
	return ""
}

type AddWordsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *AddWordsRequest) Reset() {
	*x = AddWordsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wordservice_wordservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddWordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWordsRequest) ProtoMessage() {}

func (x *AddWordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wordservice_wordservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWordsRequest.ProtoReflect.Descriptor instead.
func (*AddWordsRequest) Descriptor() ([]byte, []int) {
	return file_wordservice_wordservice_proto_rawDescGZIP(), []int{2}
}

func (x *AddWordsRequest) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type WordsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Words []*Word `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"`
}

func (x *WordsResponse) Reset() {
	*x = WordsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wordservice_wordservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordsResponse) ProtoMessage() {}

func (x *WordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wordservice_wordservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordsResponse.ProtoReflect.Descriptor instead.
func (*WordsResponse) Descriptor() ([]byte, []int) {
	return file_wordservice_wordservice_proto_rawDescGZIP(), []int{3}
}

func (x *WordsResponse) GetWords() []*Word {
	if x != nil {
		return x.Words
	}
	return nil
}

type Word struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value        string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	AddedTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=added_time,json=addedTime,proto3" json:"added_time,omitempty"`
	ModifiedTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=modified_time,json=modifiedTime,proto3" json:"modified_time,omitempty"`
	SearchCount  int64                  `protobuf:"varint,5,opt,name=search_count,json=searchCount,proto3" json:"search_count,omitempty"`
}

func (x *Word) Reset() {
	*x = Word{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wordservice_wordservice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Word) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Word) ProtoMessage() {}

func (x *Word) ProtoReflect() protoreflect.Message {
	mi := &file_wordservice_wordservice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Word.ProtoReflect.Descriptor instead.
func (*Word) Descriptor() ([]byte, []int) {
	return file_wordservice_wordservice_proto_rawDescGZIP(), []int{4}
}

func (x *Word) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Word) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Word) GetAddedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.AddedTime
	}
	return nil
}

func (x *Word) GetModifiedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedTime
	}
	return nil
}

func (x *Word) GetSearchCount() int64 {
	if x != nil {
		return x.SearchCount
	}
	return 0
}

var File_wordservice_wordservice_proto protoreflect.FileDescriptor

var file_wordservice_wordservice_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x77, 0x6f,
	0x72, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x11, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4f, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6f,
	0x72, 0x69, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6f, 0x72, 0x69, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65,
	0x77, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e,
	0x65, 0x77, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x29, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x57, 0x6f,
	0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x22, 0x38, 0x0a, 0x0d, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x05, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x05, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x22, 0xcb, 0x01, 0x0a,
	0x04, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x61,
	0x64, 0x64, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x61, 0x64, 0x64,
	0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3f, 0x0a, 0x0d, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69,
	0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0c, 0x6d, 0x6f, 0x64, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0xae, 0x02, 0x0a, 0x0b, 0x57,
	0x6f, 0x72, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5a, 0x0a, 0x08, 0x41, 0x64,
	0x64, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x1c, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x22, 0x09, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x6f,
	0x72, 0x64, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x5e, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x57, 0x6f, 0x72, 0x64, 0x12, 0x1e, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x1a, 0x09, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x6f,
	0x72, 0x64, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x63, 0x0a, 0x0a, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x57, 0x6f, 0x72, 0x64, 0x12, 0x1e, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x6f,
	0x72, 0x64, 0x73, 0x2f, 0x7b, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x7d, 0x42, 0x0e, 0x5a, 0x0c, 0x2f,
	0x77, 0x6f, 0x72, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_wordservice_wordservice_proto_rawDescOnce sync.Once
	file_wordservice_wordservice_proto_rawDescData = file_wordservice_wordservice_proto_rawDesc
)

func file_wordservice_wordservice_proto_rawDescGZIP() []byte {
	file_wordservice_wordservice_proto_rawDescOnce.Do(func() {
		file_wordservice_wordservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_wordservice_wordservice_proto_rawDescData)
	})
	return file_wordservice_wordservice_proto_rawDescData
}

var file_wordservice_wordservice_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_wordservice_wordservice_proto_goTypes = []interface{}{
	(*SearchWordRequest)(nil),     // 0: wordservice.SearchWordRequest
	(*UpdateWordRequest)(nil),     // 1: wordservice.UpdateWordRequest
	(*AddWordsRequest)(nil),       // 2: wordservice.AddWordsRequest
	(*WordsResponse)(nil),         // 3: wordservice.WordsResponse
	(*Word)(nil),                  // 4: wordservice.Word
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_wordservice_wordservice_proto_depIdxs = []int32{
	4, // 0: wordservice.WordsResponse.words:type_name -> wordservice.Word
	5, // 1: wordservice.Word.added_time:type_name -> google.protobuf.Timestamp
	5, // 2: wordservice.Word.modified_time:type_name -> google.protobuf.Timestamp
	2, // 3: wordservice.WordService.AddWords:input_type -> wordservice.AddWordsRequest
	1, // 4: wordservice.WordService.UpdateWord:input_type -> wordservice.UpdateWordRequest
	0, // 5: wordservice.WordService.SearchWord:input_type -> wordservice.SearchWordRequest
	3, // 6: wordservice.WordService.AddWords:output_type -> wordservice.WordsResponse
	3, // 7: wordservice.WordService.UpdateWord:output_type -> wordservice.WordsResponse
	3, // 8: wordservice.WordService.SearchWord:output_type -> wordservice.WordsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_wordservice_wordservice_proto_init() }
func file_wordservice_wordservice_proto_init() {
	if File_wordservice_wordservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wordservice_wordservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchWordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wordservice_wordservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wordservice_wordservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddWordsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wordservice_wordservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wordservice_wordservice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Word); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wordservice_wordservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wordservice_wordservice_proto_goTypes,
		DependencyIndexes: file_wordservice_wordservice_proto_depIdxs,
		MessageInfos:      file_wordservice_wordservice_proto_msgTypes,
	}.Build()
	File_wordservice_wordservice_proto = out.File
	file_wordservice_wordservice_proto_rawDesc = nil
	file_wordservice_wordservice_proto_goTypes = nil
	file_wordservice_wordservice_proto_depIdxs = nil
}
